site_name: Infosec Getting Started
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    accent: green
    primary: black
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://infosec.exchange/@gradius
      name: gradius

plugins:
  - search
  - tags
  - offline

repo_url: https://github.com/gradiuscypher/infosec_getting_started/
repo_name: infosec_getting_started
